### ISSUE TITLE
ImportError: cannot import name patterns

### ISSUE THREAD

**Issue by zivanovicb** [arneb/django-messages#85] opened 2017-02-13 22:16 UTC
I included url conf in urls.py:

`url(r'^messages/', include('django_messages.urls'))`

And I get this:

`File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\management\commands\runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\management\base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\management\base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\urls\resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\urls\resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "c:\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\zivan\Desktop\lobokus-django\lobokus\lobokus\urls.py", line 45, in <module>
    url(r'^messages/', include('django_messages.urls')),
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\conf\urls\__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django_messages\urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns`

**Comment by arneb** [comment] 2017-02-13 22:17
Duplicate of https://github.com/arneb/django-messages/issues/69

Please use current master branch until the new version is available on PyPI.

**Closed by arneb** 2017-02-13 22:17 UTC
