### ISSUE TITLE
django_messages.Message.sender: (fields.E320)

### ISSUE THREAD

**Issue by Ramenky27** [arneb/django-messages#113] opened 2018-06-06 11:23 UTC
While i trying to migrate after install i get message:

SystemCheckError: System check identified some issues:

ERRORS:
django_messages.Message.sender: (fields.E320) Field specifies on_delete=SET_NULL, but cannot be null. HINT: Set null=True argument on the field, or change the on_delete rule.

**Comment by arneb** [comment] 2018-06-06 12:34
Duplicate of #112

**Closed by arneb** 2018-06-06 12:34 UTC
